#!/usr/bin/env python

import rospy
import time

from zzz_common.params import parse_private_args
from zzz_driver_msgs.msg import RigidBodyStateStamped
from zzz_navigation_msgs.msg import Map
from zzz_cognition_msgs.msg import DrivingSpace, MapState
from zzz_perception_msgs.msg import DetectionBoxArray, TrackingBoxArray
from zzz_cognition_object_locator import DrivingSpaceConstructor
from visualization_msgs.msg import Marker, MarkerArray

class DrivingSpaceNode(object):
    def __init__(self):

        params = parse_private_args(
            objects_topic = "/zzz/perception/objects_tracked",
            map_input_topic="/zzz/navigation/local_static_map",
            map_output_topic="local_dynamic_map/map_with_objects",
            pose_topic = "/zzz/navigation/ego_pose",
            traffic_light_topic = "/zzz/perception/traffic_lights",
            hz=5,
        )

        self._driving_space = DrivingSpaceConstructor()
        self._rate = rospy.Rate(params.hz)

        self._dynamic_map_publisher = rospy.Publisher(params.map_output_topic, MapState, queue_size=1)

        self._pose_subscriber = rospy.Subscriber(params.pose_topic, RigidBodyStateStamped, self._driving_space.receive_ego_state)
        self._surrounding_vehicle_subscriber = rospy.Subscriber(params.objects_topic, TrackingBoxArray, self._driving_space.receive_object_list)
        self._static_map_subscriber = rospy.Subscriber(params.map_input_topic, Map, self._driving_space.receive_static_map)
        self._traffic_light_subscriber = rospy.Subscriber(params.traffic_light_topic, DetectionBoxArray,
            self._driving_space.receive_traffic_light_detection)

        #visualization
        self._obstacles_markerarray_publisher = rospy.Publisher("obstacles_markerarray", MarkerArray, queue_size=1)
        self._obstacles_label_markerarray_publisher = rospy.Publisher("obstacles_label_markerarray", MarkerArray, queue_size=1)
        self._lanes_markerarray_publisher = rospy.Publisher("lanes_markerarray", MarkerArray, queue_size=1)
        self._lanes_boundary_markerarray_publisher = rospy.Publisher("lanes_boundary_markerarray", MarkerArray, queue_size=1)
        self._ego_markerarray_publisher = rospy.Publisher("ego_markerarray", MarkerArray, queue_size=1)
        self._drivable_area_markerarray_publisher = rospy.Publisher("drivable_area_markerarray", MarkerArray, queue_size=1)
        self._next_drivable_area_markerarray_publisher = rospy.Publisher("next_drivable_area_markerarray", MarkerArray, queue_size=1)
        self._next_lanes_markerarray_publisher = rospy.Publisher("next_lanes_markerarray", MarkerArray, queue_size=1)
        self._next_lanes_boundary_markerarray_publisher = rospy.Publisher("next_lanes_boundary_markerarray", MarkerArray, queue_size=1)
    
    def loop(self):
        while not rospy.is_shutdown():
            self._rate.sleep()
            
            succss_update = self._driving_space.update_driving_space()

            if succss_update:
                self._dynamic_map_publisher.publish(self._driving_space.dynamic_map)
                self._obstacles_markerarray_publisher.publish(self._driving_space.obstacles_markerarray)
                self._obstacles_label_markerarray_publisher.publish(self._driving_space.obstacles_label_markerarray)
                self._lanes_markerarray_publisher.publish(self._driving_space.lanes_markerarray)
                self._lanes_boundary_markerarray_publisher.publish(self._driving_space.lanes_boundary_markerarray)
                self._ego_markerarray_publisher.publish(self._driving_space.ego_markerarray)
                self._drivable_area_markerarray_publisher.publish(self._driving_space.drivable_area_markerarray)
                self._next_drivable_area_markerarray_publisher.publish(self._driving_space.next_drivable_area_markerarray)
                self._next_lanes_markerarray_publisher.publish(self._driving_space.next_lanes_markerarray)
                self._next_lanes_boundary_markerarray_publisher.publish(self._driving_space.next_lanes_boundary_markerarray)


if __name__ == "__main__":
    rospy.init_node("driving_space", log_level=rospy.INFO)
    
    node = DrivingSpaceNode()
    node.loop()
